/** @type {{ dialogue: string, movie: string, year: number, hint: string }[]} */
export const questions = [
  { dialogue: "You can't handle the truth!", movie: "A Few Good Men", year: 1992, hint: "Military courtroom drama with Tom Cruise and Jack Nicholson" },
  { dialogue: "I'll be back.", movie: "The Terminator", year: 1984, hint: "Arnold Schwarzenegger as a time-travelling cyborg" },
  { dialogue: "May the Force be with you.", movie: "Star Wars: A New Hope", year: 1977, hint: "The original space opera. Episode IV." },
  { dialogue: "To infinity and beyond!", movie: "Toy Story", year: 1995, hint: "Pixar's first feature film. A space ranger toy." },
  { dialogue: "Why so serious?", movie: "The Dark Knight", year: 2008, hint: "Heath Ledger's iconic performance as the Joker" },
  { dialogue: "You talkin' to me?", movie: "Taxi Driver", year: 1976, hint: "Robert De Niro alone in front of a mirror" },
  { dialogue: "I see dead people.", movie: "The Sixth Sense", year: 1999, hint: "Haley Joel Osment whispers this to Bruce Willis" },
  { dialogue: "Life is like a box of chocolates — you never know what you're gonna get.", movie: "Forrest Gump", year: 1994, hint: "Tom Hanks sitting on a bench telling his life story" },
  { dialogue: "I am your father.", movie: "The Empire Strikes Back", year: 1980, hint: "Darth Vader's most famous revelation. Episode V." },
  { dialogue: "Here's looking at you, kid.", movie: "Casablanca", year: 1942, hint: "Humphrey Bogart. Paris. War. Romance." },
  { dialogue: "You're gonna need a bigger boat.", movie: "Jaws", year: 1975, hint: "Steven Spielberg's shark thriller" },
  { dialogue: "Here's Johnny!", movie: "The Shining", year: 1980, hint: "Jack Nicholson axes through a bathroom door" },
  { dialogue: "I'll have what she's having.", movie: "When Harry Met Sally", year: 1989, hint: "Famous diner scene with Meg Ryan" },
  { dialogue: "Say hello to my little friend!", movie: "Scarface", year: 1983, hint: "Al Pacino as Tony Montana with a big gun" },
  { dialogue: "Roads? Where we're going, we don't need roads.", movie: "Back to the Future", year: 1985, hint: "Doc Brown and a DeLorean time machine" },
  { dialogue: "I'm gonna make him an offer he can't refuse.", movie: "The Godfather", year: 1972, hint: "Marlon Brando as Don Corleone" },
  { dialogue: "Hasta la vista, baby.", movie: "Terminator 2: Judgment Day", year: 1991, hint: "Schwarzenegger returns — this time as the good guy" },
  { dialogue: "Do or do not. There is no try.", movie: "The Empire Strikes Back", year: 1980, hint: "Yoda training Luke in the swamps of Dagobah" },
  { dialogue: "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.", movie: "The Princess Bride", year: 1987, hint: "A swashbuckling revenge fairy tale" },
  { dialogue: "There is no spoon.", movie: "The Matrix", year: 1999, hint: "Neo visits a child in a waiting room" },
  { dialogue: "You shall not pass!", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, hint: "Gandalf faces the Balrog on a bridge" },
  { dialogue: "I am Groot.", movie: "Guardians of the Galaxy", year: 2014, hint: "Vin Diesel voices a tree. Those are his only words." },
  { dialogue: "E.T. phone home.", movie: "E.T. the Extra-Terrestrial", year: 1982, hint: "Spielberg's alien wants to go back" },
  { dialogue: "Get busy living, or get busy dying.", movie: "The Shawshank Redemption", year: 1994, hint: "Tim Robbins and Morgan Freeman in prison" },
  { dialogue: "Carpe diem. Seize the day, boys.", movie: "Dead Poets Society", year: 1989, hint: "Robin Williams as an inspiring English teacher" },
  { dialogue: "You is kind, you is smart, you is important.", movie: "The Help", year: 2011, hint: "Viola Davis as Aibileen speaking to a child" },
  { dialogue: "I am serious. And don't call me Shirley.", movie: "Airplane!", year: 1980, hint: "Classic spoof comedy. Leslie Nielsen." },
  { dialogue: "This is Sparta!", movie: "300", year: 2006, hint: "Gerard Butler kicks someone into a very deep pit" },
  { dialogue: "You're a wizard, Harry.", movie: "Harry Potter and the Philosopher's Stone", year: 2001, hint: "Hagrid delivers the news to a boy under the stairs" },
  { dialogue: "They may take our lives, but they'll never take our freedom!", movie: "Braveheart", year: 1995, hint: "Mel Gibson as William Wallace before battle" },
  { dialogue: "Houston, we have a problem.", movie: "Apollo 13", year: 1995, hint: "Tom Hanks in a very bad situation in space" },
  { dialogue: "I'm the king of the world!", movie: "Titanic", year: 1997, hint: "Leonardo DiCaprio at the bow of the ship" },
  { dialogue: "I feel the need — the need for speed!", movie: "Top Gun", year: 1986, hint: "Tom Cruise as Maverick, fighter pilot" },
  { dialogue: "Show me the money!", movie: "Jerry Maguire", year: 1996, hint: "Cuba Gooding Jr. on the phone with Tom Cruise" },
  { dialogue: "Nobody puts Baby in a corner.", movie: "Dirty Dancing", year: 1987, hint: "Patrick Swayze rescuing Jennifer Grey at a party" },
  { dialogue: "Oh yes, the past can hurt. But you can either run from it or learn from it.", movie: "The Lion King", year: 1994, hint: "Rafiki hits Simba with a stick to make a point" },
  { dialogue: "You had me at hello.", movie: "Jerry Maguire", year: 1996, hint: "Renée Zellweger stops Tom Cruise mid-speech" },
  { dialogue: "What is this? A center for ants?", movie: "Zoolander", year: 2001, hint: "Ben Stiller examines a tiny model of a school" },
  { dialogue: "I'm not even supposed to be here today!", movie: "Clerks", year: 1994, hint: "Kevin Smith's black-and-white convenience store comedy" },
  { dialogue: "Keep your friends close, but your enemies closer.", movie: "The Godfather Part II", year: 1974, hint: "Al Pacino as the more dangerous Michael Corleone" },
  { dialogue: "If you build it, he will come.", movie: "Field of Dreams", year: 1989, hint: "Kevin Costner hears a voice and builds a baseball diamond in a cornfield" },
  { dialogue: "Forget it, Jake. It's Chinatown.", movie: "Chinatown", year: 1974, hint: "Film noir with Jack Nicholson as a private detective" },
  { dialogue: "Get to the choppa!", movie: "Predator", year: 1987, hint: "Arnold Schwarzenegger in a jungle against an alien hunter" },
  { dialogue: "I'm walking here!", movie: "Midnight Cowboy", year: 1969, hint: "Dustin Hoffman improvised this when a real cab cut them off filming" },
  { dialogue: "You can't sit with us!", movie: "Mean Girls", year: 2004, hint: "Rachel McAdams as Regina George at a high school cafeteria" },
  { dialogue: "I volunteer as tribute!", movie: "The Hunger Games", year: 2012, hint: "Jennifer Lawrence steps forward to save her sister" },
  { dialogue: "Stupid is as stupid does.", movie: "Forrest Gump", year: 1994, hint: "Tom Hanks responding to being called stupid" },
  { dialogue: "Every time a bell rings, an angel gets its wings.", movie: "It's a Wonderful Life", year: 1946, hint: "Christmas classic with James Stewart as George Bailey" },
  { dialogue: "I love the smell of napalm in the morning.", movie: "Apocalypse Now", year: 1979, hint: "Robert Duvall on a Vietnam beach" },
  { dialogue: "What we've got here is a failure to communicate.", movie: "Cool Hand Luke", year: 1967, hint: "Paul Newman as a rebellious prisoner" },
  { dialogue: "Bond. James Bond.", movie: "Dr. No", year: 1962, hint: "Sean Connery introduces himself at a casino table" },
  { dialogue: "I'm as mad as hell, and I'm not going to take this anymore!", movie: "Network", year: 1976, hint: "Peter Finch as a news anchor having a breakdown on live TV" },
  { dialogue: "Frankly, my dear, I don't give a damn.", movie: "Gone with the Wind", year: 1939, hint: "Clark Gable walks out on Vivien Leigh" },
  { dialogue: "After all, tomorrow is another day.", movie: "Gone with the Wind", year: 1939, hint: "Scarlett O'Hara's final line, standing in the ruins of Tara" },
  { dialogue: "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", movie: "The Silence of the Lambs", year: 1991, hint: "Anthony Hopkins as Hannibal Lecter behind glass" },
  { dialogue: "That's my secret, Captain. I'm always angry.", movie: "The Avengers", year: 2012, hint: "Bruce Banner's explanation before turning into the Hulk" },
  { dialogue: "I am Iron Man.", movie: "Avengers: Endgame", year: 2019, hint: "Tony Stark's last words before snapping his fingers" },
  { dialogue: "You should have gone for the head.", movie: "Avengers: Infinity War", year: 2018, hint: "Thanos says this after Starlord ruins the plan" },
  { dialogue: "I could do this all day.", movie: "Captain America: The First Avenger", year: 2011, hint: "Steve Rogers getting beaten up in an alley before the super serum" },
  { dialogue: "I find your lack of faith disturbing.", movie: "Star Wars: A New Hope", year: 1977, hint: "Darth Vader Force-chokes an Imperial officer" },
  { dialogue: "Help me, Obi-Wan Kenobi. You're my only hope.", movie: "Star Wars: A New Hope", year: 1977, hint: "Princess Leia's hologram message inside R2-D2" },
  { dialogue: "It's a trap!", movie: "Star Wars: Return of the Jedi", year: 1983, hint: "Admiral Ackbar realises too late. A meme was born." },
  { dialogue: "The Dude abides.", movie: "The Big Lebowski", year: 1998, hint: "Jeff Bridges as a bowling-obsessed man in a robe" },
  { dialogue: "We accept the love we think we deserve.", movie: "The Perks of Being a Wallflower", year: 2012, hint: "Logan Lerman and Emma Watson. High school coming-of-age." },
  { dialogue: "Just keep swimming.", movie: "Finding Nemo", year: 2003, hint: "Dory's philosophy. Ellen DeGeneres as a forgetful blue fish." },
  { dialogue: "Oh, I'm sorry. Did I break your concentration?", movie: "Pulp Fiction", year: 1994, hint: "Samuel L. Jackson mid-monologue in an apartment" },
  { dialogue: "I'm going to make him an offer he can't refuse.", movie: "The Godfather", year: 1972, hint: "Marlon Brando. Already a classic before it even came out." },
  { dialogue: "Get away from her, you bitch!", movie: "Aliens", year: 1986, hint: "Sigourney Weaver in a power loader suit facing the Alien Queen" },
  { dialogue: "I drink your milkshake!", movie: "There Will Be Blood", year: 2007, hint: "Daniel Day-Lewis as an oil baron. Bowling alley finale." },
  { dialogue: "You can't stop what's coming.", movie: "No Country for Old Men", year: 2007, hint: "Javier Bardem as Anton Chigurh with a coin" },
  { dialogue: "We're all pretty bizarre. Some of us are just better at hiding it.", movie: "The Breakfast Club", year: 1985, hint: "Five students in Saturday detention at Shermer High" },
  { dialogue: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", movie: "Ferris Bueller's Day Off", year: 1986, hint: "Matthew Broderick speaking directly to the camera" },
  { dialogue: "I'm not a smart man, but I know what love is.", movie: "Forrest Gump", year: 1994, hint: "Tom Hanks at Jenny's grave" },
  { dialogue: "First rule of Fight Club: you do not talk about Fight Club.", movie: "Fight Club", year: 1999, hint: "Brad Pitt's character laying down the rules" },
  { dialogue: "I'm having an old friend for dinner.", movie: "The Silence of the Lambs", year: 1991, hint: "Hannibal Lecter's final phone call from a tropical location" },
  { dialogue: "Just when I thought I was out, they pull me back in.", movie: "The Godfather Part III", year: 1990, hint: "Al Pacino as an older Michael Corleone trying to go straight" },
  { dialogue: "Mama always said life was like a box of chocolates.", movie: "Forrest Gump", year: 1994, hint: "Tom Hanks quoting his mother on a park bench" },
  { dialogue: "They're here.", movie: "Poltergeist", year: 1982, hint: "A little girl announces something unsettling about the TV" },
  { dialogue: "I ate his liver with some fava beans and a nice Chianti.", movie: "The Silence of the Lambs", year: 1991, hint: "Anthony Hopkins describing a meal" },
  { dialogue: "I'm the Dude. So that's what you call me.", movie: "The Big Lebowski", year: 1998, hint: "Jeff Bridges introduces himself. Multiple times." },
  { dialogue: "Hasta la vista, baby.", movie: "Terminator 2: Judgment Day", year: 1991, hint: "The T-800 is about to fire at something frozen" },
  { dialogue: "I want to play a game.", movie: "Saw", year: 2004, hint: "A puppet on a tricycle. Jigsaw's opening words." },
  { dialogue: "We're gonna need a bigger boat.", movie: "Jaws", year: 1975, hint: "Roy Scheider sees the shark up close for the first time" },
  { dialogue: "My precious.", movie: "The Lord of the Rings: The Two Towers", year: 2002, hint: "Andy Serkis as Gollum. He loves his ring." },
  { dialogue: "You know nothing, Jon Snow.", movie: "Game of Thrones", year: 2011, hint: "Ygritte's favourite thing to say to Jon" },
  { dialogue: "Winter is coming.", movie: "Game of Thrones", year: 2011, hint: "House Stark's words. Season 1." },
  { dialogue: "I am no man.", movie: "The Lord of the Rings: The Return of the King", year: 2003, hint: "Éowyn removes her helmet to face the Witch-king" },
  { dialogue: "One does not simply walk into Mordor.", movie: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, hint: "Boromir in the Council of Elrond. Also a legendary meme." },
  { dialogue: "With great power comes great responsibility.", movie: "Spider-Man", year: 2002, hint: "Uncle Ben's words that Peter Parker carries forever" },
  { dialogue: "I'm Batman.", movie: "Batman Begins", year: 2005, hint: "Christian Bale's raspy answer when someone asks who he is" },
  { dialogue: "Why do we fall? So we can learn to pick ourselves up.", movie: "Batman Begins", year: 2005, hint: "Michael Caine as Alfred to a young Bruce Wayne" },
  { dialogue: "Wakanda forever.", movie: "Black Panther", year: 2018, hint: "Chadwick Boseman's iconic crossed-arms salute" },
  { dialogue: "I solemnly swear that I am up to no good.", movie: "Harry Potter and the Prisoner of Azkaban", year: 2004, hint: "The activation phrase for the Marauder's Map" },
  { dialogue: "Expecto Patronum!", movie: "Harry Potter and the Prisoner of Azkaban", year: 2004, hint: "Harry conjures a stag to fight Dementors" },
  { dialogue: "So it is written, so it shall be.", movie: "The Ten Commandments", year: 1956, hint: "Yul Brynner as Pharaoh Rameses" },
  { dialogue: "Let's get dangerous.", movie: "Darkwing Duck", year: 1991, hint: "The caped duck hero's catchphrase. Saturday morning cartoons." },
  { dialogue: "Yippee-ki-yay.", movie: "Die Hard", year: 1988, hint: "Bruce Willis as John McClane. Usually followed by something unprintable." },
  { dialogue: "Nobody puts Baby in a corner.", movie: "Dirty Dancing", year: 1987, hint: "Patrick Swayze defending Jennifer Grey's right to dance" },
  { dialogue: "You complete me.", movie: "Jerry Maguire", year: 1996, hint: "Tom Cruise in a living room full of women" },
  { dialogue: "I'm king of the world!", movie: "Titanic", year: 1997, hint: "Leo stretches his arms at the bow. Before the iceberg." },
  { dialogue: "Hasta la vista, baby.", movie: "Terminator 2: Judgment Day", year: 1991, hint: "Arnold. Frozen villain. Shotgun." },
];

/** @param {number} count */
export function getRandomQuestions(count = 10) {
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

/** @param {string} correctMovie @param {number} count */
export function getWrongOptions(correctMovie, count = 3) {
  const others = questions
    .filter(q => q.movie !== correctMovie)
    .map(q => q.movie);
  const unique = [...new Set(others)];
  const shuffled = unique.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
